name: Deploy
on:
  push:
    branches: [main]
permissions:
  contents: read
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.0.0-rc.10
      - name: Cache dependencies
        working-directory: static
        run: deno task cache
      - name: Build
        run: ./scripts/build.tsx
      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: explain-scanf
          entrypoint: main.ts
          import-map: generated_import_map.json
