name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1"
      - run: ./scripts/build.tsx
      - uses: denoland/deployctl@v1
        with:
          project: explain-scanf
          entrypoint: main.ts
